const currencies = {
  'AED': 'United Arab Emirates dirham',
  'AFN': 'Afghan afghani',
  'ALL': 'Albanian lek',
  'AMD': 'Armenian dram',
  'ANG': 'Netherlands Antillean guilder',
  'AOA': 'Angolan kwanza',
  'ARS': 'Argentine peso',
  'AUD': 'Australian dollar',
  'AWG': 'Aruban florin',
  'AZN': 'Azerbaijani manat',
  'BAM': 'Bosnia and Herzegovina convertible mark',
  'BBD': 'Barbados dollar',
  'BDT': 'Bangladeshi taka',
  'BGN': 'Bulgarian lev',
  'BHD': 'Bahraini dinar',
  'BIF': 'Burundian franc',
  'BMD': 'Bermudian dollar',
  'BND': 'Brunei dollar',
  'BOB': 'Boliviano',
  'BRL': 'Brazilian real',
  'BSD': 'Bahamian dollar',
  'BTN': 'Bhutanese ngultrum',
  'BWP': 'Botswana pula',
  'BYN': 'New Belarusian ruble',
  'BYR': 'Belarusian ruble',
  'BZD': 'Belize dollar',
  'CAD': 'Canadian dollar',
  'CDF': 'Congolese franc',
  'CHF': 'Swiss franc',
  'CLF': 'Unidad de Fomento',
  'CLP': 'Chilean peso',
  'CNY': 'Renminbi|Chinese yuan',
  'COP': 'Colombian peso',
  'CRC': 'Costa Rican colon',
  'CUC': 'Cuban convertible peso',
  'CUP': 'Cuban peso',
  'CVE': 'Cape Verde escudo',
  'CZK': 'Czech koruna',
  'DJF': 'Djiboutian franc',
  'DKK': 'Danish krone',
  'DOP': 'Dominican peso',
  'DZD': 'Algerian dinar',
  'EGP': 'Egyptian pound',
  'ERN': 'Eritrean nakfa',
  'ETB': 'Ethiopian birr',
  'EUR': 'Euro',
  'FJD': 'Fiji dollar',
  'FKP': 'Falkland Islands pound',
  'GBP': 'Pound sterling',
  'GEL': 'Georgian lari',
  'GHS': 'Ghanaian cedi',
  'GIP': 'Gibraltar pound',
  'GMD': 'Gambian dalasi',
  'GNF': 'Guinean franc',
  'GTQ': 'Guatemalan quetzal',
  'GYD': 'Guyanese dollar',
  'HKD': 'Hong Kong dollar',
  'HNL': 'Honduran lempira',
  'HRK': 'Croatian kuna',
  'HTG': 'Haitian gourde',
  'HUF': 'Hungarian forint',
  'IDR': 'Indonesian rupiah',
  'ILS': 'Israeli new shekel',
  'INR': 'Indian rupee',
  'IQD': 'Iraqi dinar',
  'IRR': 'Iranian rial',
  'ISK': 'Icelandic króna',
  'JMD': 'Jamaican dollar',
  'JOD': 'Jordanian dinar',
  'JPY': 'Japanese yen',
  'KES': 'Kenyan shilling',
  'KGS': 'Kyrgyzstani som',
  'KHR': 'Cambodian riel',
  'KMF': 'Comoro franc',
  'KPW': 'North Korean won',
  'KRW': 'South Korean won',
  'KWD': 'Kuwaiti dinar',
  'KYD': 'Cayman Islands dollar',
  'KZT': 'Kazakhstani tenge',
  'LAK': 'Lao kip',
  'LBP': 'Lebanese pound',
  'LKR': 'Sri Lankan rupee',
  'LRD': 'Liberian dollar',
  'LSL': 'Lesotho loti',
  'LYD': 'Libyan dinar',
  'MAD': 'Moroccan dirham',
  'MDL': 'Moldovan leu',
  'MGA': 'Malagasy ariary',
  'MKD': 'Macedonian denar',
  'MMK': 'Myanmar kyat',
  'MNT': 'Mongolian tögrög',
  'MOP': 'Macanese pataca',
  'MRO': 'Mauritanian ouguiya',
  'MUR': 'Mauritian rupee',
  'MVR': 'Maldivian rufiyaa',
  'MWK': 'Malawian kwacha',
  'MXN': 'Mexican peso',
  'MXV': 'Mexican Unidad de Inversion',
  'MYR': 'Malaysian ringgit',
  'MZN': 'Mozambican metical',
  'NAD': 'Namibian dollar',
  'NGN': 'Nigerian naira',
  'NIO': 'Nicaraguan córdoba',
  'NOK': 'Norwegian krone',
  'NPR': 'Nepalese rupee',
  'NZD': 'New Zealand dollar',
  'OMR': 'Omani rial',
  'PAB': 'Panamanian balboa',
  'PEN': 'Peruvian Sol',
  'PGK': 'Papua New Guinean kina',
  'PHP': 'Philippine peso',
  'PKR': 'Pakistani rupee',
  'PLN': 'Polish złoty',
  'PYG': 'Paraguayan guaraní',
  'QAR': 'Qatari riyal',
  'RON': 'Romanian leu',
  'RSD': 'Serbian dinar',
  'RUB': 'Russian ruble',
  'RWF': 'Rwandan franc',
  'SAR': 'Saudi riyal',
  'SBD': 'Solomon Islands dollar',
  'SCR': 'Seychelles rupee',
  'SDG': 'Sudanese pound',
  'SEK': 'Swedish krona',
  'SGD': 'Singapore dollar',
  'SHP': 'Saint Helena pound',
  'SLL': 'Sierra Leonean leone',
  'SOS': 'Somali shilling',
  'SRD': 'Surinamese dollar',
  'SSP': 'South Sudanese pound',
  'STD': 'São Tomé and Príncipe dobra',
  'SVC': 'Salvadoran colón',
  'SYP': 'Syrian pound',
  'SZL': 'Swazi lilangeni',
  'THB': 'Thai baht',
  'TJS': 'Tajikistani somoni',
  'TMT': 'Turkmenistani manat',
  'TND': 'Tunisian dinar',
  'TOP': 'Tongan paʻanga',
  'TRY': 'Turkish lira',
  'TTD': 'Trinidad and Tobago dollar',
  'TWD': 'New Taiwan dollar',
  'TZS': 'Tanzanian shilling',
  'UAH': 'Ukrainian hryvnia',
  'UGX': 'Ugandan shilling',
  'USD': 'United States dollar',
  'UYI': 'Uruguay Peso en Unidades Indexadas',
  'UYU': 'Uruguayan peso',
  'UZS': 'Uzbekistan som',
  'VEF': 'Venezuelan bolívar',
  'VND': 'Vietnamese đồng',
  'VUV': 'Vanuatu vatu',
  'WST': 'Samoan tala',
  'XAF': 'Central African CFA franc',
  'XCD': 'East Caribbean dollar',
  'XOF': 'West African CFA franc',
  'XPF': 'CFP franc',
  'XXX': 'No currency',
  'YER': 'Yemeni rial',
  'ZAR': 'South African rand',
  'ZMW': 'Zambian kwacha',
  'ZWL': 'Zimbabwean dollar'
}

const countries = {
  'AF': 'Afghanistan',
  'AL': 'Albania',
  'DZ': 'Algeria',
  'AS': 'American Samoa',
  'AD': 'Andorra',
  'AO': 'Angola',
  'AI': 'Anguilla',
  'AQ': 'Antarctica',
  'AG': 'Antigua and Barbuda',
  'AR': 'Argentina',
  'AM': 'Armenia',
  'AW': 'Aruba',
  'AU': 'Australia',
  'AT': 'Austria',
  'AZ': 'Azerbaijan',
  'BS': 'Bahamas (the)',
  'BH': 'Bahrain',
  'BD': 'Bangladesh',
  'BB': 'Barbados',
  'BY': 'Belarus',
  'BE': 'Belgium',
  'BZ': 'Belize',
  'BJ': 'Benin',
  'BM': 'Bermuda',
  'BT': 'Bhutan',
  'BO': 'Bolivia (Plurinational State of)',
  'BQ': 'Bonaire, Sint Eustatius and Saba',
  'BA': 'Bosnia and Herzegovina',
  'BW': 'Botswana',
  'BV': 'Bouvet Island',
  'BR': 'Brazil',
  'IO': 'British Indian Ocean Territory (the)',
  'BN': 'Brunei Darussalam',
  'BG': 'Bulgaria',
  'BF': 'Burkina Faso',
  'BI': 'Burundi',
  'CV': 'Cabo Verde',
  'KH': 'Cambodia',
  'CM': 'Cameroon',
  'CA': 'Canada',
  'KY': 'Cayman Islands (the)',
  'CF': 'Central African Republic (the)',
  'TD': 'Chad',
  'CL': 'Chile',
  'CN': 'China',
  'CX': 'Christmas Island',
  'CC': 'Cocos (Keeling) Islands (the)',
  'CO': 'Colombia',
  'KM': 'Comoros (the)',
  'CD': 'Congo (the Democratic Republic of the)',
  'CG': 'Congo (the)',
  'CK': 'Cook Islands (the)',
  'CR': 'Costa Rica',
  'HR': 'Croatia',
  'CU': 'Cuba',
  'CW': 'Curaçao',
  'CY': 'Cyprus',
  'CZ': 'Czechia',
  'CI': 'Côte d\'Ivoire',
  'DK': 'Denmark',
  'DJ': 'Djibouti',
  'DM': 'Dominica',
  'DO': 'Dominican Republic (the)',
  'EC': 'Ecuador',
  'EG': 'Egypt',
  'SV': 'El Salvador',
  'GQ': 'Equatorial Guinea',
  'ER': 'Eritrea',
  'EE': 'Estonia',
  'SZ': 'Eswatini',
  'ET': 'Ethiopia',
  'FK': 'Falkland Islands (the) [Malvinas]',
  'FO': 'Faroe Islands (the)',
  'FJ': 'Fiji',
  'FI': 'Finland',
  'FR': 'France',
  'GF': 'French Guiana',
  'PF': 'French Polynesia',
  'TF': 'French Southern Territories (the)',
  'GA': 'Gabon',
  'GM': 'Gambia (the)',
  'GE': 'Georgia',
  'DE': 'Germany',
  'GH': 'Ghana',
  'GI': 'Gibraltar',
  'GR': 'Greece',
  'GL': 'Greenland',
  'GD': 'Grenada',
  'GP': 'Guadeloupe',
  'GU': 'Guam',
  'GT': 'Guatemala',
  'GG': 'Guernsey',
  'GN': 'Guinea',
  'GW': 'Guinea-Bissau',
  'GY': 'Guyana',
  'HT': 'Haiti',
  'HM': 'Heard Island and McDonald Islands',
  'VA': 'Holy See (the)',
  'HN': 'Honduras',
  'HK': 'Hong Kong',
  'HU': 'Hungary',
  'IS': 'Iceland',
  'IN': 'India',
  'ID': 'Indonesia',
  'IR': 'Iran (Islamic Republic of)',
  'IQ': 'Iraq',
  'IE': 'Ireland',
  'IM': 'Isle of Man',
  'IL': 'Israel',
  'IT': 'Italy',
  'JM': 'Jamaica',
  'JP': 'Japan',
  'JE': 'Jersey',
  'JO': 'Jordan',
  'KZ': 'Kazakhstan',
  'KE': 'Kenya',
  'KI': 'Kiribati',
  'KP': 'Korea (the Democratic People\'s Republic of)',
  'KR': 'Korea (the Republic of)',
  'KW': 'Kuwait',
  'KG': 'Kyrgyzstan',
  'LA': 'Lao People\'s Democratic Republic (the)',
  'LV': 'Latvia',
  'LB': 'Lebanon',
  'LS': 'Lesotho',
  'LR': 'Liberia',
  'LY': 'Libya',
  'LI': 'Liechtenstein',
  'LT': 'Lithuania',
  'LU': 'Luxembourg',
  'MO': 'Macao',
  'MG': 'Madagascar',
  'MW': 'Malawi',
  'MY': 'Malaysia',
  'MV': 'Maldives',
  'ML': 'Mali',
  'MT': 'Malta',
  'MH': 'Marshall Islands (the)',
  'MQ': 'Martinique',
  'MR': 'Mauritania',
  'MU': 'Mauritius',
  'YT': 'Mayotte',
  'MX': 'Mexico',
  'FM': 'Micronesia (Federated States of)',
  'MD': 'Moldova (the Republic of)',
  'MC': 'Monaco',
  'MN': 'Mongolia',
  'ME': 'Montenegro',
  'MS': 'Montserrat',
  'MA': 'Morocco',
  'MZ': 'Mozambique',
  'MM': 'Myanmar',
  'NA': 'Namibia',
  'NR': 'Nauru',
  'NP': 'Nepal',
  'NL': 'Netherlands (the)',
  'NC': 'New Caledonia',
  'NZ': 'New Zealand',
  'NI': 'Nicaragua',
  'NE': 'Niger (the)',
  'NG': 'Nigeria',
  'NU': 'Niue',
  'NF': 'Norfolk Island',
  'MP': 'Northern Mariana Islands (the)',
  'NO': 'Norway',
  'OM': 'Oman',
  'PK': 'Pakistan',
  'PW': 'Palau',
  'PS': 'Palestine, State of',
  'PA': 'Panama',
  'PG': 'Papua New Guinea',
  'PY': 'Paraguay',
  'PE': 'Peru',
  'PH': 'Philippines (the)',
  'PN': 'Pitcairn',
  'PL': 'Poland',
  'PT': 'Portugal',
  'PR': 'Puerto Rico',
  'QA': 'Qatar',
  'MK': 'Republic of North Macedonia',
  'RO': 'Romania',
  'RU': 'Russian Federation (the)',
  'RW': 'Rwanda',
  'RE': 'Réunion',
  'BL': 'Saint Barthélemy',
  'SH': 'Saint Helena, Ascension and Tristan da Cunha',
  'KN': 'Saint Kitts and Nevis',
  'LC': 'Saint Lucia',
  'MF': 'Saint Martin (French part)',
  'PM': 'Saint Pierre and Miquelon',
  'VC': 'Saint Vincent and the Grenadines',
  'WS': 'Samoa',
  'SM': 'San Marino',
  'ST': 'Sao Tome and Principe',
  'SA': 'Saudi Arabia',
  'SN': 'Senegal',
  'RS': 'Serbia',
  'SC': 'Seychelles',
  'SL': 'Sierra Leone',
  'SG': 'Singapore',
  'SX': 'Sint Maarten (Dutch part)',
  'SK': 'Slovakia',
  'SI': 'Slovenia',
  'SB': 'Solomon Islands',
  'SO': 'Somalia',
  'ZA': 'South Africa',
  'GS': 'South Georgia and the South Sandwich Islands',
  'SS': 'South Sudan',
  'ES': 'Spain',
  'LK': 'Sri Lanka',
  'SD': 'Sudan (the)',
  'SR': 'Suriname',
  'SJ': 'Svalbard and Jan Mayen',
  'SE': 'Sweden',
  'CH': 'Switzerland',
  'SY': 'Syrian Arab Republic',
  'TW': 'Taiwan',
  'TJ': 'Tajikistan',
  'TZ': 'Tanzania, United Republic of',
  'TH': 'Thailand',
  'TL': 'Timor-Leste',
  'TG': 'Togo',
  'TK': 'Tokelau',
  'TO': 'Tonga',
  'TT': 'Trinidad and Tobago',
  'TN': 'Tunisia',
  'TR': 'Turkey',
  'TM': 'Turkmenistan',
  'TC': 'Turks and Caicos Islands (the)',
  'TV': 'Tuvalu',
  'UG': 'Uganda',
  'UA': 'Ukraine',
  'AE': 'United Arab Emirates (the)',
  'GB': 'United Kingdom of Great Britain and Northern Ireland (the)',
  'UM': 'United States Minor Outlying Islands (the)',
  'US': 'United States of America (the)',
  'UY': 'Uruguay',
  'UZ': 'Uzbekistan',
  'VU': 'Vanuatu',
  'VE': 'Venezuela (Bolivarian Republic of)',
  'VN': 'Viet Nam',
  'VG': 'Virgin Islands (British)',
  'VI': 'Virgin Islands (U.S.)',
  'WF': 'Wallis and Futuna',
  'EH': 'Western Sahara',
  'YE': 'Yemen',
  'ZM': 'Zambia',
  'ZW': 'Zimbabwe',
  'AX': 'Åland Islands'
};

const country_codes = Object.keys(countries)
const currency_codes = Object.keys(currencies)
const interest_types = ['FIXED', 'FLOATING']
const financing_request_types = ['AUTOMATIC', 'ON REQUEST']
const program_types = ['APPROVED PAYABLE FINANCE', 'RECEIVABLE FINANCE','DISTRIBUTOR FINANCE']
const program_statuses = ['ONBOARDING', 'INACTIVE' ,'ACTIVE', 'BLACKLISTED']
const invoice_statuses = ['UPLOADED', 'SENT FOR APPROVAL', 'APPROVED', 'FINANCE REQUESTED', 'FINANCED']
const party_roles = ['BUYER', 'SELLER', 'HYBRID']
const customer_statuses= ['ONBOARDING', 'APPROVED', 'REJECTED']
export {
  currency_codes,
  currencies,
  country_codes,
  countries,
  interest_types,
  program_statuses,
  invoice_statuses,
  financing_request_types,
  program_types,
  party_roles,
  customer_statuses
};

